### ISSUE TITLE
Add notifications for text messages

### ISSUE THREAD

**Issue by Fadorico** [Bathlamos/RTDC#108]

**Comment by Shern** [comment]
What is missing: 
- Solve Hibernate Mapping Exception
- Send a HTTP REST request to GCM server when we want to send a notifications.
- Implement a listener for GCM messages.
- Create a notification view (?)
- Revise how GCM tokens are managed. (One per user ? A device group per user ?)

**Comment by Nicolas-M** [comment]
See #130. We added notifications for text messages using a method which depends on Liblinphone (I think). Although this was not the ideal implementation, it is the best we can do given the time left on the project.
