### ISSUE TITLE
Code GCM servlet and others in rtdc.web

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#114]
Code the servlet tha tis repsonsible to add the tokens to the table and to retrieve tokens for an user. Code the object for the token with Hibernate.

**Comment by Nicolas-M** [comment]
See #130. Notifications (for missed calls & text messages) have been implemented using the existing methods that may depend on Liblinphone. Although this is not the ideal solution, it is the best one given the time left on the project.

See also #108.
