### ISSUE TITLE
Libphone uses hardcoded password

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#115]
Asterisk requires a password. At the moment, it's a hardcoded String, but in reality, it should be obtained from the user and sent to the Asterisk server on login.

**Comment by Nicolas-M** [comment]
I assume that we're using a generated salt for that Asterisk password so that we don't have to store and constantly exchange the user's actual password. Can you confirm this @Fadorico ?

**Comment by Fadorico** [comment]
Yes, that's correct. The Asterisk password is a salt generated when we add the user to the DB. There is no relation between the user's actual password and the Asterisk password.
