### ISSUE TITLE
Cancel Button Not in All Edit Activities

### ISSUE THREAD

**Issue by Olivier004** [Bathlamos/RTDC#121]
When modifying units or users, there is no cancel button. However, there is a cancel button when editing an action or unit capacity.

**Comment by Nicolas-M** [comment]
As discussed, I removed the cancel button throughout the application. The reasoning was that there are already 2 ways to go back (the hardware back button & the back arrow [top left corner]). If it really is a problem, the cancel buttons can easily be added back.
