### ISSUE TITLE
User is not deleted when using deleteUser in UserServlet

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#134]

**Comment by Fadorico** [comment]
For some reason if we try to delete a user using the local database, it does not work and the server throws a ClassCastException: String cannot be cast to Number. However if we're using the Heroku database, everything works. I'm not sure why that is, but the main difference I can see between the two in the hibernate.cfg.xml file is that the local database uses org.hsqldb.jdbcDriver as its driver while the Heroku database uses org.postgresql.Driver.

**Comment by Nicolas-M** [comment]
I've just spent hours looking into this and I don't think that our code is the root of the issue. As you've mentionned, it works on Heroku. This leads me to believe that we're encoutering a bug with HSQLDB. Thus, I changed our local database to use Apache Derby. Everything appears to be working now, including the delete user. Closing issue.
