### ISSUE TITLE
Editing a unit erases the data for that unit in the Capacity Overview

### ISSUE THREAD

**Issue by Fadorico** [Bathlamos/RTDC#137]
After editing a unit through the Manage Units interface, all other values for this unit are set to 0 in the Capacity Overview.

**Comment by Nicolas-M** [comment]
I understand the bug, but when fixing it, we should keep in mind that editing the total number of beds of a unit might affect the other values. For example, if I change the `Total Beds` from **32** down to **16**, and that `Beds Available` is set to **24**, then the one of the values is invalid...

**Comment by Shern** [comment]
Resolved. Added confirmation dialog when changing Total of beds.
