### ISSUE TITLE
Setup Server

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#14]
* Get a server
* Install a Linux distribution (Ubuntu, CentOS, etc.)
* Install Team Viewer
* Install VMware or Virtual Box
* Create an AsteriskNOW vm
* Install Couchbase Server
* Install Couchbase Sync

**Comment by Nicolas-M** [comment]
Olivier has extra RAM. Hopefully, that will do the trick.

**Comment by Nicolas-M** [comment]
The added RAM helped. Couchbase Server and Couchbase Sync Gateway have been installed. Bucket shadowing has been configured properly, based on these [instructions](http://developer.couchbase.com/mobile/develop/guides/sync-gateway/wcbs/bucket-shadowing/index.html) on creating a json config file.

No-IP has also been installed and configured. The server is now accessible via http://rtdc.legault.cc:4984 (Sync Gateway) or http://rtdc.legault.cc:8091 (Server console).

**Comment by Nicolas-M** [comment]
From what I understand, Mathieu's server is all setup. Can we close this issue?

**Comment by Shern** [comment]
I'm guesing that yes we can.
