### ISSUE TITLE
 User Is Redirected to Manage Units After Login

### ISSUE THREAD

**Issue by Olivier004** [Bathlamos/RTDC#141]
User is redirected to manage units instead of capacity overview when he logs in. When he starts up the app already logged in, capacity overview opens up, just like it should.

**Comment by Fadorico** [comment]
This bug was fixed indirectly when we added the concept of permissions on the client side. Only Admins are sent to Manage Units while Managers are sent to the Capacity Overview and Users are sent to the Action Plan.
