### ISSUE TITLE
Test SIP library

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#17]
We need a library that would allow users to communicate between each other through the Asterisk Server. Here is a list of tasks we seek to test / accomplish:
* Determine a user's status
* Send a message to a user
* Call a user
* Video call a user
* etc.

After some research, we found a library that could do the job. It's called [PJSIP](http://www.pjsip.org/). It should support most platforms including Android and iOS. The only downside is that it's licensed under GPL. In other words, our project needs to be open-source for us to use the library for free (unless I'm mistaken).

**Comment by Fadorico** [comment]
Tested Asterisk connection using a program called Zoiper and was able to successfully make a "Hello World" call. This issue will be put on hold for the time being so that we can address more urging tasks.

**Comment by Fadorico** [comment]
It was found that not all android devices supported the API for SIP; it is up to the manufacturer to decide if it wants to support it or not. Therefor, we are now exploring a library called Liblinphone. This issue will be closed as the library was found to be working Asterisk.
