### ISSUE TITLE
Administrator Interface

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#22]
* Create Android Module
* Implement the interface for the following:
 * Create Account
 * View / Manage Accounts
 * Create Unit
 * View / Create Unit

**Comment by Nicolas-M** [comment]
Android module has been created and committed. Interface still requires implementation.

**Comment by Shern** [comment]
Create User and Create Unit are done. What is missing:
- Access User and Unit information from the lists.
- Save modifications for both.

**Comment by Nicolas-M** [comment]
What's missing now: Add a delete method in the controller.

**Comment by Shern** [comment]
Completed. Bugs are in a different issue.
