### ISSUE TITLE
Capacity Overview Interface

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#23]
Create the interface for the Capacity Overview page. (Visible to unit managers).

**Comment by Bathlamos** [comment]
Il faut maintenant finaliser le Capacity Overview, de manière à 

1. Ajouter/modifier/enlever des rangées SPÉCIFIQUES (en ce moment, on peut seulement éditer la première colonne)
2. Parvenir à scroller lorsque nécéssaire
3. Appeler le serveur pour synchroniser les données (brancher le backend)
4. Header statique

 Oliviiiiier :)

**Comment by Olivier004** [comment]
- Capacity overview data is now pulled from the server
- Rows can be edited but need to fix row sorting bug (row order keeps changing between edit saves)
- Need to implement data push to server when edits are saved
- Need to implement row sorting on column title tap

**Comment by Nicolas-M** [comment]
Capacity Overview has been implemented, and is connected to the database. Closing issue.
