### ISSUE TITLE
Gradle:GWT error running Android module

### ISSUE THREAD

**Issue by Olivier004** [Bathlamos/RTDC#28]
Syncing the gradle project works fine. However, when I try to run it, IntelliJ / Gradle gives me the following errors:

*Error:gradle: execution failed for task ':core:compilegwt'. > process 'command 'c:\program files\java\jdk1.7.0_75\bin\java.exe'' finished with non-zero exit value 1*

*Warning:Gradle: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.*

**Comment by Olivier004** [comment]
We managed to fix the warning (i.e. the second message)  by creating a few keys in the Windows Registry:

1) Start -> regedit.exe
2) Make sure the following keys exist. If not, right click on the folder where they should be, and select new key:
* HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Prefs
* HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Prefs
* HKEY_CURRENT_USER\Software\JavaSoft\Prefs

**Comment by Bathlamos** [comment]
When GWT can't compile, run the Gradle task compileGWT to see a more detailed error message.
