### ISSUE TITLE
Poor Form Validation

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#29]
An interface named "ValidatorWidget" under the impl package needs to be created in the Core, and implemented in Android, under the impl package.

That interface has the following methods:
getText, setText, getError (as String), setError(String)

The goal of the Widget is to show error messages below an input (like a textbox) when the user enters incorrect values.

We NEED to have more than just textboxes supported. For instance, we'd like to also have that widget support Dropdown Input. Find a way to do that, but it may be done in round 2 of processing this issue.

**Comment by Olivier004** [comment]
Validation widget implemented for text boxes (EditText in Android).

**Comment by Fadorico** [comment]
Raw notes of what we've discussed that should be validated

````
add-edit user
	(server) password: at least one number, one letter and length >= 8
	courriel: validate
	password confirmation for password
	rename employee number to username (title)
	first and last name: no symbols and no numbers. Allow hypens
add-edit unit
	name: any character (symbol included)
	# of beds: make sure its a number. keypad is numeric but make sure still. bigger ot equal then 0
add-edit capacity
	available beds: <= total beds
	potential dc: <= total beds
	dc by deadline: <= potential dc
	total admits: no restrictions
	admits by deadline: <= total admits
	
	For all: make sure its numbers only
add-edit action
	role: no restrictions
	description: length <= 2500
	deadline: regex for time (##:##)
````

**Comment by Fadorico** [comment]
Text boxes are validated on the client before the data is sent over to the server, where it gets validated again for safe measure. Both the client and the server use the same validation rules, which are stored within the Core.
