### ISSUE TITLE
Validation des objets

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#32]
Nos objets ne dépendent plus de Hibernate validator ou de JSR 303. Nous allons appliquer nos propres méthodes de valitation.

Ajout de la méthode validate(), qui retourne un ensemble de ConstraintViolation objects, inspirés de JSR 303.

**Comment by Fadorico** [comment]
We now have a class named SimpleValidator that helps validate objects. Validation is done on both the client side and the server side for good mesure.
