### ISSUE TITLE
Asterisk SIP audio call

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#38]
Établir une communication audio entre deux appareils Android.

La tâche est complété lorsque
- sur un appareil Android, on initie une connexion à Asterisk.
- Asterisk communique avec un second appareil Android.
- la connection est acceptée.
- on peut parler d'un appareil Android à l'autre.

**Comment by Fadorico** [comment]
En utilisant la librairie Liblinphone, les tâches suivantes on été accompli:

- Sur un appareil Android, on initie une connexion à Asterisk.
- Asterisk communique avec un second appareil Android.

**Comment by Fadorico** [comment]
Un appel à été fait avec succès en utilisant deux téléphones Android, tout les deux utilisant la librairie Liblinphone.
