### ISSUE TITLE
Integrate Asterisk into RTDC

### ISSUE THREAD

**Issue by Fadorico** [Bathlamos/RTDC#49]
RTDC must access Asterisk's database in order to register users and make calls from one user to another.

**Comment by Bathlamos** [comment]
I disagree with that statement. Surely, there must be some other way to integrate with Asterisk.

**Comment by Fadorico** [comment]
I was under the impression that RTDC would use SQL requests in order to register/delete information in Asterisk. What else do you suggest? Or maybe my initial comment was misleading?

**Comment by Bathlamos** [comment]
RTDC server must use an official API of some sort, for interaction with Asterisk. It is the only way that we'll be guaranteed that our changes do not break anything.

**Comment by Fadorico** [comment]
After discussion, it was decided that we should investigate the Asterisk-Java library (https://maven.reucon.com/projects/public/asterisk-java/1.0.0.CI-SNAPSHOT/asterisk-java/index.html)

**Comment by Fadorico** [comment]
It seems that Asterisk-Java provides many useful features, but adding/removing users in real time is not one of them. We're probably going to have to use Asterisk Realtime, an addon, to be able to do this.

**Comment by Fadorico** [comment]
Users and extensions are added to Asterisk when RTDC creates new users. An audio call can be made to new users by calling their extension (which currently is the user's RTDC ID).
