### ISSUE TITLE
Replace icons with Material icons

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#55]

**Comment by Nicolas-M** [comment]
Replaced all the icons with the Material ones (commit 53f7f76d8b1644bd3f71bf488d572ee433c7d2b0)

Things to note:
* Icons can be found [here](https://www.google.com/design/icons/)
* Although the icons are 24 dp at the moment, the touch target size [should always be 48 dp.] (http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-touch-target-size)
* [Tinting](https://developer.android.com/training/material/drawables.html) can only be added in API 21
* Padding should probably be added, especially for the login. @Bathlamos, can you help with this?

**Comment by Nicolas-M** [comment]
I think we're used to the little padding that the icons have now. It's not that big of a deal.
