### ISSUE TITLE
Redesign dialogs

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#58]
Title then input is not the preferred way. We wish to use the design from the Quora app.

**Comment by Nicolas-M** [comment]
Not too sure what was the Quora design, but I opted to add cards to everything, and categorizing the content into these cards. Let me know if you had something else in mind!

**Comment by Nicolas-M** [comment]
@Bathlamos Approved the design. The textviews could go next to their labels, but we should be good for now.
