### ISSUE TITLE
Test API

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#79]
Create tests for the server using JUnit.

**Comment by Nicolas-M** [comment]
We fixed most of the tests. See d236312d63f0613745b7803e283eb621eb250344. Essentially, there was a problem with the HTTP requests that were being made in the test class. If you're making a GET or DELETE request, it does not expect to have urlParameters. In other words, that parameter needs to be ```null``` instead of ```""```

**Comment by Shern** [comment]
Done, 47 tests, with only one failing.
