### ISSUE TITLE
Communication Hub UI

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#81]
Create the communication hub UI. It should allow users to do the following:
* Send a new message
* Scroll through their previous messages
* Highlight unread messages.
* View a conversation with another user
* Divide the conversation according to the date
* Have buttons to contact (audio / video call) a user.

Here is the old mockup for inspiration:
![rtdc - communication hub](https://cloud.githubusercontent.com/assets/7707423/9839900/db6ec35c-5a54-11e5-96af-a7f8abaeb1a0.png)

There`s also a screeshot of Hipchat on Dropbox. I suggest you check it out when building the UI for conversations.

**Comment by Olivier004** [comment]
Mostly done. Need to:
- Identify unread messages in recent contacts list view
- Assign blue color to messages sent from self
- Group consecutive messages
- Group messages by date

**Comment by Nicolas-M** [comment]
I was lucky enough to get a preview of the interface. It looks fantastic! :) Keep it up.

**Comment by Olivier004** [comment]
- Identify unread messages in recent contacts list view (Done)
- Assign color to messages sent from self (Buggy)
- Group consecutive messages (Buggy)
- Group messages by date

Background color of list view items seems to change randomly when scrolling (breaks color assigning feature). Order of messages in array list also seems to be random when the list loads (breaks message grouping feature).

**Comment by Olivier004** [comment]
- Identify unread messages in recent contacts list view (Done)
- Assign color to messages sent from self (Done)
- Group consecutive messages (Done)
- Group messages by date (TO DO)

Order of messages in list view needs some testing to confirm the bug is fixed.

**Comment by Olivier004** [comment]
- Identify unread messages in recent contacts list view (Done)
- Assign color to messages sent from self (Done)
- Group consecutive messages (Done)
- Group messages by date (Done)
