### ISSUE TITLE
Freezing on Sign out

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#91]
The app stops responding from time to time when a user tries to log out. I'm not sure if it's the server's fault, or Android. I think it's Android... Also, I've only noticed this problem since the drawer menu was redesigned. Maybe the two are connected?

**Comment by Fadorico** [comment]
Could not reproduce. Closing issue.

**Comment by Nicolas-M** [comment]
Still happening, but after talking to Jonathan, we suspect that a lack of connection to the Asterisk server might be related to the issue.

**Comment by Fadorico** [comment]
These lines of code might be the cause of the issue

        // Let the Liblinphone thread unregister

        while(currentProxyConfig.getState() != LinphoneCore.RegistrationState.RegistrationCleared) {
            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
````

**Comment by Nicolas-M** [comment]
Mathieu & Olivier say that it seems that the sign out no longer freezes following the fix. Closing issue.
