### ISSUE TITLE
Objects are not refreshed when opened from a list

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#94]
For example, if I open the list of actions, and someone modify an action, this action is not refreshed when I open it to modify it. So ideally we would want to check if the object is updated when opening an activity to modify it. Either reload the entire list or implement new calls in the service to get a single object instead of the list. Modify Android code accordingly.

**Comment by Olivier004** [comment]
Hint: Store updated object as cache and update it when fragment is reloaded. Potential problem: how to notify the fragment that an object has been updated or added?

**Comment by Olivier004** [comment]
Bug mostly resolves. Some things have to be considered:
- Updating a capacity inverts the sorting order of Capacity Overview when user doesn't click on a column header initially (incorrect lastClicked variable value at first?)
- When updating a user or a unit, the objects are updated in the list but the alphabetical order isn't rearranged. Do we want to rearrange it?
